sudo: required

language: go

go:
  - 1.15

services:
  - docker

cache:
  directories:
    - cache/

env:
  global:
    - CGO_ENABLED=0
    - GOBUILD="linux-amd64"
    - GOMODCACHE="/home/travis/gopath/src/github.com/seatgeek/docker-mirror/cache/go/mod"
    - GOCACHE="/home/travis/gopath/src/github.com/seatgeek/docker-mirror/cache/go/build"

script:
  - make -j dist
  - ls -la build

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file:
    - build/docker-mirror-linux-amd64
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: seatgeek/docker-mirror
